import { useEffect, useMemo, useState } from "react";
import api from "../services/api";

type Movement = { id:string; type:string; quantity:number|string; createdAt:string; product:{sku:string;name:string}; warehouse:{code:string;name:string}; user:{name:string} };
const labels:Record<string,string>={IN:"Entrada",OUT:"Saída",TRANSFER:"Transferência",ADJUSTMENT:"Ajuste"};

export default function Reports(){
  const [metrics,setMetrics]=useState<any>(); const [moves,setMoves]=useState<Movement[]>([]); const [type,setType]=useState(""); const [from,setFrom]=useState(""); const [to,setTo]=useState(""); const [loading,setLoading]=useState(false);
  async function load(){setLoading(true); try { const [m,r]=await Promise.all([api.get('/reports/dashboard'),api.get('/reports/movements',{params:{...(type?{type}:{}),...(from?{from:new Date(from).toISOString()}:{}),...(to?{to:new Date(to+'T23:59:59').toISOString()}: {})}})]); setMetrics(m.data.metrics); setMoves(r.data.items); } finally {setLoading(false);} }
  useEffect(()=>{load()},[]);
  const totals=useMemo(()=>moves.reduce((a,m)=>{a[m.type]=(a[m.type]||0)+Number(m.quantity);return a},{} as Record<string,number>),[moves]);
  function exportCsv(){const header=['Data','Tipo','SKU','Produto','Quantidade','Armazém','Usuário'];const rows=moves.map(m=>[new Date(m.createdAt).toLocaleString('pt-BR'),labels[m.type]??m.type,m.product.sku,m.product.name,m.quantity,m.warehouse.name,m.user.name]);const csv=[header,...rows].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`logi-ject-movimentacoes-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);}
  return <section className="page report-page"><div className="page-header"><div><h1>Relatórios</h1><p>Indicadores e movimentações operacionais.</p></div><div className="header-actions"><button onClick={()=>window.print()} className="secondary">Imprimir / PDF</button><button onClick={exportCsv}>Exportar CSV</button></div></div>
    {metrics&&<div className="metrics metrics-4"><Metric value={metrics.products} label="Produtos ativos"/><Metric value={metrics.totalUnits.toLocaleString('pt-BR')} label="Unidades em estoque"/><Metric value={`R$ ${metrics.totalValue.toLocaleString('pt-BR',{minimumFractionDigits:2})}`} label="Valor do estoque"/><Metric value={metrics.lowStock} label="Estoque baixo"/></div>}
    <div className="report-summary">{Object.entries(totals).map(([k,v])=><div className="summary-chip" key={k}><span>{labels[k]??k}</span><b>{v.toLocaleString('pt-BR')}</b></div>)}</div>
    <div className="table-card"><div className="table-toolbar report-toolbar"><div><h2>Movimentações</h2><span>{moves.length} registros encontrados</span></div><div className="filters"><select value={type} onChange={e=>setType(e.target.value)}><option value="">Todos os tipos</option><option value="IN">Entradas</option><option value="OUT">Saídas</option><option value="TRANSFER">Transferências</option><option value="ADJUSTMENT">Ajustes</option></select><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" value={to} onChange={e=>setTo(e.target.value)}/><button onClick={load}>{loading?'...':'Filtrar'}</button></div></div><div className="table-wrap"><table><thead><tr><th>Data</th><th>Tipo</th><th>Produto</th><th>Quantidade</th><th>Armazém</th><th>Usuário</th></tr></thead><tbody>{moves.map(x=><tr key={x.id}><td>{new Date(x.createdAt).toLocaleString('pt-BR')}</td><td><span className={`badge ${x.type==='IN'?'success':x.type==='OUT'?'danger':'muted'}`}>{labels[x.type]??x.type}</span></td><td>{x.product.sku} - {x.product.name}</td><td>{Number(x.quantity).toLocaleString('pt-BR')}</td><td>{x.warehouse.name}</td><td>{x.user.name}</td></tr>)}</tbody></table></div></div>
  </section>
}
function Metric({value,label}:{value:string|number;label:string}){return <article className="metric-card"><strong>{value}</strong><span>{label}</span></article>}
